apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-config
data:
  NODE_ENV: development
  NEXT_PUBLIC_ENVIRONMENT: development
  NEXT_PUBLIC_SOLANA_ENDPOINT: https://rpc.mainnet.holaplex.tools
  NEXT_PUBLIC_INDEXER_GRAPHQL_URL: https://graph-test.holaplex.com/v1
