name: Test

on:
  push:
  pull_request:
    branches: [dev, main]

jobs:
  test:
    name: All Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: '16'
            cache: 'yarn'
      - run: yarn install
      - run: yarn run format:check